---
- hosts: all
  sudo: true
  vars:
    #logstash_forwarder_logstash_server: ""
    #logstash_forwarder_logstash_server_port:12345
    logstash_forwarder_ssl_certificate_file: myssl.crt
    logstash_forwarder_ssl_key_file: myssl.key

  roles:
    - {role: logstash-forwarder }


