
- name: auth - ensure cert directory
  file:
    path={{ logstash_forwarder_cert | dirname }}
    state=directory

- name: auth - copy cert
  copy:
    src={{ logstash_forwarder_local_cert }}
    dest={{ logstash_forwarder_cert }}
    mode=0644
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_user }}
  notify: restart logstash-forwarder
  when: logstash_forwarder_sll_copy_local

- name: auth - ensure CA directory
  file:
    path={{ logstash_forwarder_ca | dirname }}
    state=directory

- name: auth - copy ca
  copy:
    src={{ logstash_forwarder_local_ca }}
    dest={{ logstash_forwarder_ca }}
    mode=0644
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_user }}
  notify: restart logstash-forwarder
  when: logstash_forwarder_sll_copy_local

- name: auth - ensure private key directory
  file:
    path={{ logstash_forwarder_key | dirname }}
    state=directory

- name: auth - copy private key
  copy:
    src={{ logstash_forwarder_local_key }}
    dest={{ logstash_forwarder_key }}
    mode=0600
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_user }}
  notify: restart logstash-forwarder
  when: logstash_forwarder_sll_copy_local

- name: ensure rights to private key
  file:
    path={{ logstash_forwarder_key }}
    state=file
    mode=0600
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_user }}
  notify: restart logstash-forwarder

