---

- name: config - set owner of logstash
  file:
    state=directory
    path=/opt/logstash-forwarder/bin
    recurse=yes
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_group }}

- name: Config - create directories
  file:
    state=directory
    path={{ item }}
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_group }}
  with_items:
    - "/etc/logstash-forwarder"
    - "/var/log/logstash-forwarder"

- name: Config - logstash-forwarder
  template:
    src=logstash-forwarder.json.j2
    dest=/etc/logstash-forwarder/logstash-forwarder.json
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_group }}
    mode=0644
  notify: restart logstash-forwarder

- name: Config - watch files
  template:
    src=watch-files.json.j2
    dest=/etc/logstash-forwarder/watch.json
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_group }}
    mode=0644
  notify: restart logstash-forwarder

