---
- name: logstash forwarder - install debian
  include: install_debian.yml
  tags:
    - install
  when: ansible_os_family == "Debian"

- name: logstash forwarder - install centos
  include: install_centos.yml
  tags:
    - install
  when: ansible_os_family == "RedHat"

- name: logstash forwarder - configure
  include: config.yml
  tags:
    - config 

- name: logstash forwarder - auth
  include: auth.yml
  tags:
    - config

- name: logstash forwarder - service
  include: service.yml
  tags:
    - service
  vars:
    service_name: logstash-forwarder
    service_user: "{{logstash_forwarder_user}}"
    service_group: adm
    service_command: /opt/logstash-forwarder/bin/logstash-forwarder -config /etc/logstash-forwarder -spool-size 100 
    service_env_vars: {}
