---

- name: service - setup and run
  runit:
    name: logstash-forwarder
    enabled: yes
    state: start
    timeout: 10
    user: "{{ logstash_forwarder_user }}"
    command: /opt/logstash-forwarder/bin/logstash-forwarder -config /etc/logstash-forwarder/ -spool-size {{ logstash_spool_size }}
    env_vars: {}
  register: logstash_forwarder_service_status

